### ISSUE TITLE
Not possible to create datasource using Grafana 8.2.7

### ISSUE THREAD

**Issue by michael-sawczuk** [grafana/google-bigquery-datasource#121]
Attempting to create a database results in the error:
`Object(...) is not a function Evaluating https://<<REMOVED>>>/public/plugins/grafana-bigquery-datasource/module.js Loading plugins/grafana-bigquery-datasource/module`

Grafana:  8.2.7
Plugin: grafana-bigquery-datasource @ 1.1.0

**Comment by zoltanbedi** [comment]
Thanks for letting us know @michael-sawczuk looks like that the plugin is not working with 8.2.7 but works with 8.3.x and higher versions.
